config/routes.rb
CreditCardComparison::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  root to: "main#index"

  namespace :api do
    devise_for :users, path: :devise,
               controllers: { sessions: "api/devise/sessions",
                              registrations: "api/devise/registrations",
                              passwords: "api/devise/passwords"
               }
    devise_scope :api_user do
      get  "devise/current_user" => "devise/sessions#show_current_user"
      post "devise/facebook_auth" => "devise/sessions#facebook_auth"
    end
    resources :credit_cards
    resources :lists do
      collection do
        get :qualities
      end
    end
  end

  resources :credit_cards, only: :index

  get "credit_cards*path", to: "credit_cards#index"

  %w( admin admin/*path login password/recover password/reset/:password).each{ |url| get url => "admin#index" }

end

app/models/business_type.rb
class BusinessType < List
end

app/models/business_year.rb
class BusinessYear < List
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset
  include Ckeditor::Orm::Mongoid::AssetBase

  delegate :url, :current_path, :size, :content_type, :filename, :to => :data
  
  validates_presence_of :data
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, :mount_on => :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, :mount_on => :data_file_name

  def url_content
    url(:content)
  end
end

app/models/credit_card.rb
class CreditCard
  include Mongoid::Document
  include Mongoid::Slug
  field :name, type: String
  include MetaSearchMongoid
  slug :name
  field :description, type: String
  field :quality_need, type: Integer
  field :application_url, type: String
  field :loan_application_url, type: String
  field :apr_min, type: Integer
  field :apr_max, type: Integer
  field :fee, type: Integer
  field :business_accept_cards, type: Boolean, default: false

  has_and_belongs_to_many :business_types
  has_and_belongs_to_many :credit_scores
  has_and_belongs_to_many :monthly_sales
  has_and_belongs_to_many :priorities
  has_and_belongs_to_many :reward_programs
  has_and_belongs_to_many :business_years

  validates :name, uniqueness: true, on: :create
  validates :name, :description, :quality_need, :application_url, :loan_application_url, presence:  true
  validates :fee, numericality: true, allow_blank: true
  validates :apr_max, :apr_min, numericality: true
  validates :application_url, :loan_application_url, url: true
  mount_uploader :image, CardImageUploader, type: String

  def self.search(options={})
    options ||= {}
    options = options.select{|k,v| !v.blank?}
    search = Search.new(options)
    search.collection = searcher(options)
    search
  end

  def self.searcher(options)
    chain = self.scoped
    options.each do |name, val|
      chain = chain.send("by_#{name}", val)
    end
    chain
  end

  def self.by_business_type(val)
    self.where(:business_type_ids => BusinessType.find(val).id)
  end

  def self.by_business_year(val)
    self.where(:business_year_ids => BusinessYear.find(val).id)
  end

  def self.by_monthly_sale(val)
    self.where(:monthly_sale_ids => MonthlySale.find(val).id)
  end

  def self.by_priority(val)
    self.where(:priority_ids => Priority.find(val).id)
  end

  def self.by_credit_score(val)
    self.where(:credit_score_ids => CreditScore.find(val).id)
  end

  def self.by_reward_program(val)
    self.where(:reward_program_ids => RewardProgram.find(val).id)
  end

  def self.by_business_accept_cards(val)
    self.where(:business_accept_cards => val)
  end

  def quality_name
    credit_scores.pluck(:name).join(", ")
  end

  def image_data=(data)
    io = CarrierStringIO.new(Base64.decode64(data.gsub(/.*base64,/, '')))
    self.image = io
  end
end

app/models/credit_score.rb
class CreditScore < List
end

app/models/list.rb
class List
  include Mongoid::Document
  include Mongoid::Slug
  include Mongoid::Timestamps
  field :name, type: String
  slug :name
  scope :recent, ->{ order_by(:created_at => :asc) }
end

app/models/monthly_sale.rb
class MonthlySale < List
end

app/models/priority.rb
class Priority < List
end

app/models/reward_program.rb
class RewardProgram < List
end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  ## Database authenticatable
  field :email, type: String, default: ""
  field :encrypted_password, type: String, default: ""

  ## Recoverable
  field :reset_password_token, type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  layout "admin"
  def index
  end
end

app/controllers/api/base_controller.rb
class Api::BaseController < ActionController::Base
  respond_to :json
  before_filter :authenticate_api_user!
end

app/controllers/api/credit_cards_controller.rb
class Api::CreditCardsController < Api::BaseController
  before_filter :authenticate_api_user!, except: [:index, :show]

  def index
    @credit_cards = CreditCard.page(params[:page]).per(10)
    respond_with :api, @credit_cards
  end

  def show
    @credit_card = CreditCard.find(params[:id])
    respond_with :api, @credit_card
  end

  def create
    credit_card = CreditCard.new(credit_card_params)
    credit_card.save
    respond_with :api, credit_card
  end

  def update
    credit_card = CreditCard.find(params[:id])
    if credit_card.update_attributes(credit_card_params)
      render status: 200, json: credit_card.to_json
    else
      render status: 422, json: { errors: credit_card.errors }
    end
  end

  def destroy
    CreditCard.find(params[:id]).destroy
    respond_to do |format|
      format.json { render json: {notice: "CreditCard was successfully deleted!"} }
    end
  end

  private
  def credit_card_params
    params.require(:credit_card).permit(:name, :description, :quality_need, :application_url,
                                        :loan_application_url, :apr_min, :apr_max, :image_data, :business_accept_cards, credit_score_ids:[], business_year_ids:[],
                                        reward_program_ids:[], priority_ids: [], monthly_sale_ids: [], business_type_ids: [])
  end
end

app/controllers/api/lists_controller.rb
class Api::ListsController < Api::BaseController

  def index
    render json: {
                    credit_scores: CreditScore.recent,
                    monthly_sales: MonthlySale.recent,
                    rewards_program: RewardProgram.recent,
                    business_types: BusinessType.recent,
                    business_years: BusinessYear.recent,
                    priorities: Priority.recent
                 }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

app/controllers/credit_cards_controller.rb
class CreditCardsController < MainController
  before_filter :parse_seach_params
  def index
    @search = CreditCard.search(@search_params)
    @credit_cards = @search.collection
  end

  private
  def parse_seach_params
    @search_params = {}
    rules = {
      business_type: /business-type-(.+)/,
      credit_score: /credit-score-(.+)/,
      business_year: /years-in-business-(.+)/,
      monthly_sale: /monthly-sale-(.+)/,
      priority: /credit-card-type-priority-(.+)/,
      reward_program: /preferred-rewards-program-(.+)/,
      business_accept_cards: /business-accepts-credit-cards-(.+)/
    }
    pars = params.select{|k,v| k =~ /f\d+/}.values
    pars += params[:path].split("_") if params[:path]
    pars.each do |value|
      rules.each do |name, reg|
        value =~ reg
        @search_params[name] = $1 if $1
      end
    end
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    @search = Search.new({})
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def credit_card_fee(card)
    card.fee || "N/A"
  end

  def filters(search)
    atts = []
    search.attributes.each do |key, value|
      atts << "#{t(key.to_s)} : #{get_value(key,value)}"
    end
    atts.join(" | ")
  end

  def get_value(key, value)
    case key
    when :business_accept_cards
      value == "true" ? "yes" : "no"
    else
      key.to_s.classify.constantize.find(value).name
    end
  end
end

app/views/credit_cards/_credit_card.html.haml
%table.schumer-box{cellpadding: "0", cellspacing: "0"}
  %tbody
    %tr
      %td{style: "width:161px;height:1px"}
      %td{style: "width:361px;height:1px"}
      %td{style: "width:164px;height:1px"}
    %tr
      %th.offer-left{colspan: "2"}
        %table{border: "0", width: "100%"}
          %tbody
            %tr
              %td
                %a.top-pick{href: "#"}= credit_card.name
      %td.field-apply-now{align: "center", rowspan: "2"}
        %a{href: credit_card.application_url, target: "_blank"}
          = image_tag "apply-now.jpg"
    %tr
      %td.cc-card-art-align
        %a{href: "#"}
          = image_tag credit_card.image_url, size: "142x82", alt: credit_card.name
          %br
      %td.details
        = credit_card.description.html_safe
    %tr
      %td{colspan: "3"}
        %table.rate-rc{align: "center", cellpadding: "0", cellspacing: "1"}
          %tbody
            %tr
              %td.rate-top{rowspan: "2"} Regular APR
              %td.rate-top{rowspan: "2"}
                Annual Fee
              %td.rate-top.credit-needed{rowspan: "2"} Credit Needed
            %tr
            %tr
              %td.rates-bottom= "#{credit_card.apr_min}% - #{credit_card.apr_max}%"
              %td.rates-bottom= credit_card_fee(credit_card)
              %td.rates-bottom= credit_card.quality_name
%br

app/views/credit_cards/_table.html.haml
.card_style
  .schumer-box-container
    - credit_cards.each do |card|
      = render "credit_card", credit_card: card

app/views/credit_cards/index.html.haml
%section#content.clearfix{style: "min-height: 37px; padding-top:0; margin-top: -10px"}
  .bootstrapped
    .row
      .col-sm-1
      .col-sm-6
        %h1 Credit Card Comparison
        %h6= filters(@search)
  .container(style="margin-top:40px;")
    .infobox.one-fourth.filter
      = form_for @search, url: credit_cards_path, method: :get, html:{ id: "search_form" } do |f|
        %label= t("business_type")
        = f.select :business_type, BusinessType.recent.map{|b| [b.name, b.slug]}, { include_blank: "Business Type" }, id: "business-type"
        %label= t("business_year")
        = f.select :business_year, BusinessYear.recent.map{|b| [b.name, b.slug]}, { include_blank: "Years in business" }, id: "years-in-business"
        %label= t("monthly_sale")
        = f.select :monthly_sale, MonthlySale.recent.map{|b| [b.name, b.slug]}, { include_blank: "Current Monthly Sales" }, id: "monthly-sale"
        %label= t("priority")
        = f.select :priority, Priority.recent.map{|b| [b.name, b.slug]}, { include_blank: "Credit Card Type Priority" }, id: "credit-card-type-priority"
        %label= t("credit_score")
        = f.select :credit_score, CreditScore.recent.map{|b| [b.name, b.slug]}, { include_blank: "Credit Score" }, id: "credit-score"
        %label= t("reward_program")
        = f.select :reward_program, RewardProgram.recent.map{|b| [b.name, b.slug]}, { include_blank: "Preferred Rewards Program" }, id: "preferred-rewards-program"
        %label= t("business_accept_cards")
        = f.select :business_accept_cards, [["Yes", true],["No", false]], { include_blank: "Business accept credit cards" }, id: "business-accepts-credit-cards"
        %input.button{type: "submit", value: "Search", style: "background-color: #428937"}
    - if @credit_cards.empty?
      .bootstrapped
        %span(style="display:block; text-align:center;")
          %h1 No Cards found
    - else
      #credit-cards(style="float:right")
        = render "table", credit_cards: @credit_cards
    %section#content.container.clearfix{style: "padding-top:0px;margin-top:0px;"}
      %h2.slogan.align-center
      .one
        .two-third
          #lead_captured.two-third

app/views/credit_cards/index.js.haml
:plain
  $("#credit-cards").html("#{j render "table", credit_cards: @credit_cards}")

app/views/layouts/admin.html.haml
!!!
%html(ng-app="main")
  %head
    %title Credit Card Comparison Admin
    = stylesheet_link_tag "admin", media: "all"
    = javascript_include_tag "admin", "main"
    = csrf_meta_tags
  %body(ui-view)

app/views/layouts/application.html.haml
!!!
%html(ng-app="main")
  %head
    %title Credit Card Comparison
    = stylesheet_link_tag    "application", media: "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
%body
  / __________________________________________________ Start Page
  / __________________________________________________ Start Header
  %header#header-application.start-div.clearfix
    %a#logo{href: "http://www.forwardfinancing.com"}
      %img{alt: "ForwardFinancing", height: "66px", src: "//www.forwardfinancing.com/site/wp-content/uploads/2012/04/logo-home.png"}/
    .tel
      %h6 Speak with a Funding Specialist
      %h2.bullet-tel (888) 244-9099
    %nav#main-nav

  %div{style: "background-image: linear-gradient(bottom, #FFFFFF 1%, #E0E0E0 80%);background-image: -o-linear-gradient(bottom, #FFFFFF 1%, #E0E0E0 80%);\r\nbackground-image: -moz-linear-gradient(bottom, #FFFFFF 1%, #E0E0E0 80%);\r\nbackground-image: -webkit-linear-gradient(bottom, #FFFFFF 1%, #E0E0E0 80%);\r\nbackground-image: -webkit-linear-gradient(bottom, #FFFFFF 1%, #E0E0E0 80%);\r\nbackground-image: -ms-linear-gradient(bottom, #FFFFFF 1%, #E0E0E0 80%);\r\nbackground-image: -webkit-gradient(linear, left bottom, left top, color-stop(0.01, #FFFFFF), color-stop(0.51, #E0E0E0)); \r\nheight: 35px;"}
  = yield
  %footer#footer.clearfix
    .container{style: "width:1050px;"}
      .three-fourth
        %nav#footer-nav.clearfix
      .one-fourth.last
      .clear
  %footer#footer-bottom.clearfix
    .container
      %ul
        %li
          %a Forward Financing © 2013
        %li
          %a Phone: (888) 244-9099
        %li
          %a Email: info@forwardfinancing.com
        %li
          %a 36 Bromfield Street 2nd Floor Boston, MA 02108

app/views/main/index.html.haml
%section#content.container.clearfix{style: "padding-top:0px;margin-top:-40px;"}
  %h2.slogan.align-center
  .one
    .two-third
      #lead_captured.two-third
        = form_for @search, url: credit_cards_path, method: :get, html: { class: "wpcf7-form", id: "search_form" } do |f|
          %h1 Business Credit Card Comparison Engine
          %h2 Find the best business card for your business needs
          %div{style: "float:left; padding-right: 10px;"}
            %label Business Type
            = f.select :business_type, BusinessType.recent.map{|b| [b.name, b.slug]}, { include_blank: "Business Type" }, id: "business-type"
          %div{style: "float:left; padding-right: 10px;"}
            %label Years in business
            = f.select :business_year, BusinessYear.recent.map{|b| [b.name, b.slug]}, { include_blank: "Years in business" }, id: "years-in-business"
          %div{style: "clear:both"}
          %div{style: "float:left; padding-right: 10px; padding-top: 20px;"}
            %label Current Monthly Sales
            = f.select :monthly_sale, MonthlySale.recent.map{|b| [b.name, b.slug]}, { include_blank: "Current Monthly Sales" }, id: "monthly-sale"
          %div{style: "float:left; padding-right: 10px; padding-top: 20px;"}
            %label Credit Card Type Priority
            = f.select :priority, Priority.recent.map{|b| [b.name, b.slug]}, { include_blank: "Credit Card Type Priority" }, id: "credit-card-type-priority"
          %div{style: "float:left; padding-right: 10px; padding-top: 20px;"}
            %label Credit Score
            = f.select :credit_score, CreditScore.recent.map{|b| [b.name, b.slug]}, { include_blank: "Credit Score" }, id: "credit-score"
          %div{style: "float:left; padding-right: 10px; padding-top: 20px;"}
            %label Preferred Rewards Program
            = f.select :reward_program, RewardProgram.recent.map{|b| [b.name, b.slug]}, { include_blank: "Preferred Rewards Program" }, id: "preferred-rewards-program"
          %div{style: "clear:both"}
          %div{style: "float:left; padding-right: 10px; padding-top: 20px;"}
            %label Does your business accept credit cards
            = f.select :business_accept_cards, [["Yes", true],["No", false]], { include_blank: "Business accept credit cards" }, id: "business-accepts-credit-cards"

          %div{style: "clear:both"}
          %div{style: "padding-top:30px"}
            %input#lead_save.button{style: "width: 453px; background-color: #428937", type: "submit", value: "Continue now"}/
    #or_tabs.one-third.last
      .infobox
        %img{src: "//www.forwardfinancing.com/site/wp-content/themes/smartstart/images/contact.jpg", width: "100%"}/
        %h3{style: "text-align:center;"} Contact a Specialist Immediately
        #reference_number_div{style: "text-align:center; display:none;"}
          Your Reference Number:
          %h3
        %h2{style: "color:#428937; font-weight:700; text-align:center;"} (888) 244-9099
        #request_call{style: "display:none;"}
          #request_button{style: "margin-top: 15px;"}
            %input#request_call.button{onclick: "ga('send', 'event', 'Application', 'Phone Box', 'REQUEST A CALL, Reference number:'+document.getElementById('reference_number').value+'.');", style: "width: 100%; height: 40px; text-align: center;", type: "button", value: "REQUEST A CALL"}/
      / end .infobox
      .infobox
        %p{style: "font-size:11px; text-align:center;"}
          %a{href: "#", style: "color:#428937;"} Privacy & Security
          |
          %a{href: "#", style: "color:#428937;"} info@forwardfinancing.com
        %p{style: "font-size:11px; text-align:center; margin-top: -20px;"} Forward Financing® is a Registered Trademark.
        / <img width="100%" src="http://www.forwardfinancing.com/site/wp-content/themes/smartstart/images/security.jpg"></img>
        %table{border: "0", cellpadding: "2", cellspacing: "0", title: "Click to Verify - This site chose Symantec SSL for secure e-commerce and confidential communications.", width: "135"}
          %tbody
            %tr
              %td{align: "center", valign: "top", width: "135"}
                %script{src: "https://seal.verisign.com/getseal?host_name=www.forwardfinancing.com&size=L&use_flash=NO&use_transparent=NO&lang=en", type: "text/javascript"}
                %a{href: "javascript:vrsn_splash()", tabindex: "-1"}
                  %img{alt: "Click to Verify - This site has chosen an SSL Certificate to improve Web site security", border: "true", name: "seal", oncontextmenu: "return false;", src: "https://seal.verisign.com/getseal?at=0&sealid=0&dn=www.forwardfinancing.com&lang=en"}/
                %br/
        %div{align: "center"}
          %a{href: "http://www.bbb.org/boston/business-reviews/financing/dollar-merchant-financing-llc-in-boston-ma-133112/", target: "_blank"}
            %img{src: "http://www.forwardfinancing.com/site/wp-content/themes/smartstart/images/cbbb-badge-horz.png", width: "60%"}/
      / end .infobox
    :javascript
      var __lc = {};
      __lc.license = 3480682;

      (function() {
      	var lc = document.createElement('script'); lc.type = 'text/javascript'; lc.async = true;
      	lc.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'cdn.livechatinc.com/tracking.js';
      	var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(lc, s);


      })();
      var LC_API = LC_API || {};


  / end .one